# 项目类型
type: maven

# 工程名称
name: account
version: 1.4.1

# 镜像编译参数
docker:
  # 镜像名称
  image: gitlab.snz1.cn:9008/seatas/examples/account
  # 镜像编译文件(默认：Dockerfile)
  file: Dockerfile

# 编译命令
build:
- ../mvnw
- package
- -DskipTests

# 测试命令
test:
- ../mvnw
- test

# 运行命令
run:
- ../mvnw
- spring-boot:run
- -DskipTests

# 清理命令
clean:
- ../mvnw
- clean

# 服务定义
service:
  # 端口定义
  ports:
  - 9191:80

  # 环境变量
  envs:
  - CONFIG_PROFILE=prod
  - JWT_TOKEN={{ .Snz1dp.Jwt.Token }}
  - JWT_PRIVKEY={{ .Snz1dp.Jwt.PrivateKey }}
  - PG_DATABASE=seatas_example_account
  - PG_HOST={{ .Postgres.Host }}
  - PG_PORT={{ .Postgres.Port }}
  - PG_USER={{ .Postgres.Admin.Username }}
  - PG_PASSWORD={{ .Postgres.Admin.Password }}

  # 心跳检查
  healthcheck:
    url: /seatas/example/account/health
    interval: 10s
    timeout: 10s
    period: 30s
    retries: 30

  # 路由定义
  ingress:
  - backend-port: 80
    strip-path: false
    jwt:
    - /seatas/example/account

# 开发配置
develop:
  config: |
    postgres:
      admin:
        username: postgres
        password: snz1dp9527
      host: postgres
      install: true
      port: 5432
      version: "9.6"
      config:
        envs:
        - MAX_CONNECTIONS="100"
    redis:
      password: redis9527
      host: redis
      install: true
      port: 6379
      version: 4.0.11
    confserv:
      install: true
      version: 2.0.3
    snz1dp:
      admin:
        email: root@localhost.com
        username: root
        password: 123456
      ingress:
        docker:
          repo:
            host: repo.docker
            port: 80
            protocol: http
        host: localhost
        port: 80
        protocol: http
      namespace: snz1dp-system
      organization: ChangSha SNZ1
      registry:
        encoded_password: 3433f68e1891b295ae1e953cfc8c740aeaed2d5cf386a8aaf470
        url: gitlab.snz1.cn:9008
        username: demo
      timezone: Asia/Shanghai
      version: 1.0-alpha
